name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        & minikube -p minikube docker-env | Invoke-Expression


    - name: Build Docker image for Frontend
      run: |
        docker build -t taha305/my-frontend-app:latest ./client

    - name: Build Docker image for Backend
      run: |
        docker build -t taha305/my-backend-app:latest ./server

    - name: Login to Docker Hub
      shell: cmd
      run: docker login -u "taha305" -p "Muhammadtaha1@@"

    - name: Push Docker images to Docker Hub
      run: |
        docker push taha305/my-frontend-app:latest
        docker push taha305/my-backend-app:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        
